"""initial tables

Revision ID: 1e10053625a9
Revises: 
Create Date: 2025-11-24 18:34:07.447348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e10053625a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_location_tag_pair', 'location_tags', ['location_id', 'tag_id'])
    op.add_column('user_visits', sa.Column('points_earned', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('points', sa.Integer(), nullable=False))
    op.add_column('users', sa.Column('level', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'level')
    op.drop_column('users', 'points')
    op.drop_column('user_visits', 'points_earned')
    op.drop_constraint('uq_location_tag_pair', 'location_tags', type_='unique')
    # ### end Alembic commands ###
